DROP TABLE YelpUser;
DROP TABLE YelpFriend;
DROP TABLE YelpUserReview;
DROP TABLE Reviews;
DROP TABLE ReviewContent;
DROP TABLE MarkedReview;
DROP TABLE Business;
DROP TABLE BusinessCategory;
DROP TABLE BusinessPhoto;
